[package]
name = "leta-fs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "This is an internal component crate of leta"
repository.workspace = true
homepage.workspace = true

[dependencies]
fastrace = { workspace = true }
thiserror = { workspace = true }
